products:
  displayCount: 5
  sortBy: name
db:
  server:
    hostname: 127.0.0.1
    port: 27017
  database:
    name: products
    collectionName: products

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products
